### ISSUE TITLE
Typo ?

### ISSUE THREAD

**Issue by AlbertZhangHIT** [aimerykong/predictive-filter-flow#12]
Hi, 
In `PFF_image/libs_deblur/models/pixel_embedding_model.py`, 

    ...
    line 165         out = self.layer1(out)        
    line 166         out_layer1 = self.layer1_dimRed(out)        
    line 167         out_layer1 = self.interp_x4(out_layer1)
    line 167         out_layer1 = self.layer2_feats(out_layer1)
    ...
    line 366         out = self.layer1(out)        
    line 367         out_layer1 = self.layer1_dimRed(out)        
    line 368         out_layer1 = self.interp_x4(out_layer1)
    line 369         out_layer1 = self.layer2_feats(out_layer1)
    ...
    line 542         out = self.layer1(out)        
    line 543         out_layer1 = self.layer1_dimRed(out)        
    line 544         out_layer1 = self.interp_x4(out_layer1)
    line 545         out_layer1 = self.layer2_feats(out_layer1)
    ...
    line 716         out = self.layer1(out)        
    line 717         out_layer1 = self.layer1_dimRed(out)        
    line 718         out_layer1 = self.interp_x4(out_layer1)
    line 719         out_layer1 = self.layer2_feats(out_layer1)
    ...

All layer1 features you used `self.layer2_feats`, maybe there is something wrong with this.

**Comment by aimerykong** [comment]
Hi, Hao,
Yes! That is a bug! Thank you for checking the code. I also found this
recently, yet didn't have chance to update the github:-)
Hope this does not bother you too much.
Regards,
Shu
